apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher
  namespace: rancher
spec:
  rules:
  - host: myrancher.com
    http:
      paths:
      - backend:
          service:
            name: rancher
            port:
                number: 80